# Generated by Django 4.1 on 2023-10-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1Id", models.BigIntegerField()),
                ("palyer2Id", models.BigIntegerField()),
                ("moves", models.CharField(max_length=10000)),
                ("winner", models.BigIntegerField()),
            ],
        ),
    ]
