# Generated by Django 4.1 on 2023-10-29 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ChessGame", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamemodel",
            name="moves",
        ),
        migrations.RemoveField(
            model_name="gamemodel",
            name="winner",
        ),
        migrations.AddField(
            model_name="gamemodel",
            name="status",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AlterField(
            model_name="gamemodel",
            name="palyer2Id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamemodel",
            name="player1Id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
