# Generated by Django 4.0 on 2023-10-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChessGame', '0004_alter_gamemodel_palyer2id_alter_gamemodel_player1id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemodel',
            old_name='palyer2Id',
            new_name='player2Id',
        ),
    ]
