# Generated by Django 4.0 on 2023-11-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessGame', '0005_rename_palyer2id_gamemodel_player2id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='position',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
