# Generated by Django 4.0 on 2023-11-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChessGame', '0006_gamemodel_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='position',
        ),
    ]
