# Generated by Django 4.0 on 2023-11-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessGame', '0007_remove_gamemodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='position',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
