# Generated by Django 4.0 on 2023-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessGame', '0008_gamemodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='status',
            field=models.CharField(default='running', max_length=100),
        ),
    ]
