# Generated by Django 4.0 on 2023-11-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups_alter_user_user_permissions'),
        ('ChessGame', '0009_gamemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='users.user'),
        ),
    ]
