# Generated by Django 4.0 on 2023-11-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('no_of_players', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
