# Generated by Django 4.0 on 2023-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='no_of_players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='users',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
