# Generated by Django 4.0 on 2023-11-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_no_of_players_tournament_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gameIds',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
